# Generated by Django 2.2.3 on 2019-07-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dg_lunbotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField()),
                ('db_img', models.CharField(max_length=100)),
                ('db_color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eye_db_lunbotu',
            },
        ),
        migrations.CreateModel(
            name='Hot_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('productimg', models.CharField(max_length=100)),
                ('product_new_price', models.FloatField()),
                ('product_prev_price', models.FloatField()),
                ('product_level', models.CharField(max_length=100)),
                ('product_hot_num', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'eye_hot_product',
            },
        ),
        migrations.CreateModel(
            name='Show_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showname', models.CharField(max_length=40)),
                ('showimg', models.CharField(max_length=100)),
                ('showprice', models.FloatField()),
                ('show_sale', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eye_show_product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eye_user',
            },
        ),
    ]
