# Generated by Django 2.2.3 on 2019-07-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_f5_lunbotu_light'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='light',
            table='eye_light',
        ),
    ]
