# Generated by Django 2.2.3 on 2019-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_ordergoods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='eye_orderproduct',
        ),
    ]
